language: java
jdk:
    - oraclejdk8
    - openjdk8

dist: trusty
sudo: required

services:
    - docker

deploy:
    provider: script
    script: ./scripts/docker-deploy.sh
    on:
        jdk: openjdk8
